#! /bin/csh -f
rm      out
cp 	lj.model        	fort.25

#generate n values of lambda with python script
python3 listgen.py 900

set lambdas=`cat lambdas`
rm lambdas
rm lambdas.dat

foreach lambda ($lambdas)
  echo " --- lambda ${lambda} "  		>> out
  echo " --- lambda ${lambda} "  
  cat > fort.15  <<endofdata
  ibeg   nequil   prod   nsamp  iseed
  0      999     999   1      368675
  dr
  0.09 
  ndispl
  50  
  npart temp rho  lambda
  100   2.0  0.70 ${lambda}
endofdata
 cp 	lj.res          	fort.11
 cp 	lj.model          	fort.25
 time  ../Source/mc_nvt  		>>& out 
 cp 	fort.21         	lj.res
 cp 	fort.66         	lj.prt
 cat    fort.666                        >>& lambda.dat
 #perform block analysis
 cp 	lj.prth 		fort.31
 cp  	lj.prt 			fort.32
 ../Block/block  	 		>>& out 
 rm fort.*
 @ i++
end
exit



